# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.18.2
loom_version=1.14-SNAPSHOT
mod_version=0.9.2
minecraft_compat=1.21.11

# Mod Properties
maven_group=work.lclpnet.mods.kibu
archives_base_name=kibu-world-api

# Dependencies
fabric_version=0.139.5+1.21.11
fantasy_version=0.7.0+1.21.11